% Function to generate box URDF with variable height
function urdf_str = generate_box_urdf(height, box_width)

if nargin < 2
    box_width = [0.1, 0.1];
end

    urdf_str = sprintf(['<robot name="pedestal">', ...
        '<link name="base_link">', ...
        '<inertial><mass value="1000"/><inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/></inertial>', ...
        '<visual><geometry><box size="%f %f %f"/></geometry></visual>', ...
        '<collision><geometry><box size="%f %f %f"/></geometry></collision>', ...
        '</link>', ...
        '</robot>'], box_width(1), box_width(2), height, box_width(1), box_width(2), height);
end

%[appendix]{"version":"1.0"}
%---
